//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS_TUP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Denuncias
    {
        //public int IdDenuncia { get; set; }
        //public string IdTipoDenuncia { get; set; }
        //public string Descripcion { get; set; }
        //public byte[] Foto1 { get; set; }
        //public byte[] Foto2 { get; set; }
        //public byte[] Archivo { get; set; }
        //public string Fiscalia { get; set; }
        //public string UserName { get; set; }
        //public Nullable<System.DateTime> Fecha { get; set; }
        //public string activa { get; set; }
        //public byte[] Audio1 { get; set; }
        //public byte[] Audio2 { get; set; }


        public int IdDenuncia { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio.")]
        public string IdTipoDenuncia { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio.")]
        public string Descripcion { get; set; }

        public byte[] Foto1 { get; set; }
        public byte[] Foto2 { get; set; }

        public HttpPostedFileBase File { get; set; }
        public byte[] Archivo { get; set; }


        public string Fiscalia { get; set; }
        public string UserName { get; set; }

        //[Required(ErrorMessage = "Este campo es obligatorio.")]
        //[DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Fecha { get; set; }

        public string activa { get; set; }

        public byte[] Audio1 { get; set; }
        public byte[] Audio2 { get; set; }


    }
}
