//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS_TUP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Mensajes
    {
        public int IdMensaje { get; set; }
        public Nullable<int> IdDenuncia { get; set; }
        public string UserName { get; set; }
        public DateTime Fecha { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio.")]
        public string Mensaje { get; set; }
        public byte[] Imagen1 { get; set; }
        public byte[] Archivo { get; set; }
        public string Role { get; set; }
    }
}
