//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS_TUP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RedesSocEmpresas
    {
        public int IdRegRed { get; set; }
        public string UserName { get; set; }
        [Required(ErrorMessage = "Este campo es obligatorio.")]
        public string Red { get; set; }
        [Required(ErrorMessage = "Este campo es obligatorio.")]
        public string Link { get; set; }
        [Required(ErrorMessage = "Este campo es obligatorio.")]
        public string Descripcion { get; set; }
    }


    public enum TipoRedSocial
    {
        Instagram,
        Twitter,
        Facebook,
        Otra
    }
}
