//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS_TUP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoUsuario
    {
        public int id_usuario { get; set; }
        public string UserName { get; set; }
        public string DNI { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<System.DateTime> fecha_nac { get; set; }
        public string telefono { get; set; }
        public Nullable<int> idProvincia { get; set; }
        public string ciudad { get; set; }
        public string calle { get; set; }
        public string altura { get; set; }
        public string piso { get; set; }
        public string sexo { get; set; }
    }
}
