//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS_TUP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuarios
    {
        public int Id { get; set; }
        //[Required(ErrorMessage = "Este campo es obligatorio.")]
        public string UserName { get; set; }
        //[Required(ErrorMessage = "Este campo es obligatorio.")]
        public string Password { get; set; }
        public string Role { get; set; }

        //[Required(ErrorMessage = "Este campo es obligatorio.")]
        //[MaxLength(45, ErrorMessage = "Limite: 45 caracteres.")]
        public string Email { get; set; }
    }
}
